### ISSUE TITLE
sidekiq_concurrency overrides concurrency in config sidekiq.yml

### ISSUE THREAD

**Issue by linusramos** [Mic92/mina-sidekiq#13]
sidekiq command line argument "sidekiq -c " overrides concurrency in config file

`# ### sidekiq:start
  desc "Start sidekiq"
  task :start => :environment do
    queue %[echo "-----> Start sidekiq"]
    for_each_process do |pid_file, idx|
      queue  #%{
        cd "#{deploy_to}/#{current_path}"
        #{echo_cmd %[#{sidekiq} -d -e #{rails_env} -C #{sidekiq_config} **-c #{sidekiq_concurrency}** -i #{idx} -P #{pid_file} -L #{sidekiq_log}] }
      }
    end
  end
`

pull request #12 removes sidekiq_concurrency

**Comment by Mic92** [comment]
fixed in https://github.com/Mic92/mina-sidekiq/commit/1396706b5414290c6bd2330f84c6addb9d879251
