### ISSUE TITLE
[Question] - Does pending jobs get deleted when we deploy new release of our Rails app?

### ISSUE THREAD

**Issue by zulhfreelancer** [Mic92/mina-sidekiq#21]
Hi,

Just curious to know. Say before deployment I have 10 pending jobs in Redis.

1. After deployment of new release of my Rails app, does that 10 pending jobs get deleted?

2. Are they 'safe' and persisted in Redis database during deployment process?

3. Does Sidekiq auto-fetch pending jobs in Redis after each new deployment or just ignore them?

Thanks!

**Comment by Mic92** [comment]
Before every upgrade the old sidekiq instance is told to no longer accept new jobs and only finish the remaining one sidekiq has already started processing:  https://github.com/Mic92/mina-sidekiq/blob/master/lib/mina_sidekiq/tasks.rb#L76
The new sidekiq master will be already started after that and start processing jobs.
After the old is finished processing with its remaining task, it will just stop.
Unprocessed jobs will stay in Redis. There is a chapter in documentation explaining the safety levels Redis provide: https://redis.io/topics/persistence
It could be that jobs get lost, if sidekiq crashes during loading a job. This message will be lost then. There is a payed version of sidekiq, called sidekiq pro which counter measure this case: http://sidekiq.org/products/pro
But this is out of the scope what my library does.

**Comment by zulhfreelancer** [comment]
Thanks!
