### ISSUE TITLE
`environment` task is deprecated

### ISSUE THREAD

**Issue by x-yuri** [Mic92/mina-sidekiq#26]
https://github.com/mina-deploy/mina/blob/master/docs/migrating.md#dsl
https://github.com/mina-deploy/mina/issues/569
https://github.com/mina-deploy/mina/commit/972a26ce354e8031a0656c16783c02390c821e33#diff-7c4278fbad7ef1bfaa3f199ba9d6c0adR6

**Comment by Mic92** [comment]
@devvmh where would be `invoke :'rvm:use', ENV.fetch('RUBY_VERSION', 'ruby-2.3.1')` added then?

**Comment by Mic92** [comment]
I do no longer work on rails projects at the moment, but I would accept pull requests.

**Comment by x-yuri** [comment]
`mina` now has 2 tasks: `local_environment` and `remote_environment`. In other words, all tasks that depend on `environment` are to depend on `remote_environment`. If I understand you correctly.

Or maybe dependency on `environment` task is to be removed altogether. Which is not clear from the docs.

**Comment by devvmh** [comment]
Ohh, I see where there might be a problem - mina has deprecated environment. I was thinking we were talking about a PR in mina-sidekiq.

Regardless, I was able to make it work using the existing mina-sidekiq code.

Do you have an issue that you're able to solve with https://github.com/Mic92/mina-sidekiq/pull/27 ?

**Comment by x-yuri** [comment]
@devvmh sort of, it displays deprecation warning.

**Comment by devvmh** [comment]
OK, that makes sense. I'll help to review your PR
