### ISSUE TITLE
Sidekiq 6.0 fail

### ISSUE THREAD

**Issue by lewislinlin** [Mic92/mina-sidekiq#32]
ERROR: Daemonization mode was removed in Sidekiq 6.0, please use a proper process supervisor to start and manage your services
FYI: https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md

**Comment by huobazi** [comment]
+1

**Comment by Mic92** [comment]
I would merge pull requests, but I am not going to fix this on my own.
I am not using mina, rails or sidekiq since years.
If somebody wants to take over maintenance ...

**Comment by Mic92** [comment]
Fixed in https://github.com/Mic92/mina-sidekiq/pull/33
