### ISSUE TITLE
Problem sidekiq 6

### ISSUE THREAD

**Issue by igortice** [Mic92/mina-sidekiq#35]
![Captura de Tela 2020-06-17 às 12 17 35](https://user-images.githubusercontent.com/1306646/84916523-8fa7ab00-b094-11ea-94aa-a660ffa1ab7d.png)

![Captura de Tela 2020-06-17 às 12 16 21](https://user-images.githubusercontent.com/1306646/84916546-97674f80-b094-11ea-8c76-7b2f321822f0.png)

![Captura de Tela 2020-06-17 às 12 14 33](https://user-images.githubusercontent.com/1306646/84916566-9cc49a00-b094-11ea-8417-7503e5feb65c.png)

![Captura de Tela 2020-06-17 às 12 18 53](https://user-images.githubusercontent.com/1306646/84916690-c1207680-b094-11ea-9ece-2eeb30fde6b0.png)

**Comment by Mic92** [comment]
I assume this was fixed in master: https://github.com/Mic92/mina-sidekiq/pull/33
I am not really using this anymore but still merge pull requests, I guess I can create new release.

**Comment by veverkap** [comment]
Can you do a new release?

**Comment by clousky2020** [comment]
I also have this problem. Without this task, can you tell me how to get this task

**Comment by Mic92** [comment]
I published 1.1.0
