### ISSUE TITLE
Cannot restart sidekiq

### ISSUE THREAD

**Issue by charlatan154** [Mic92/mina-sidekiq#4]
Seems that re/start doesn't work for me. The only way to start sidekiq is when i removed 'nohup' command, but then sidekiq stop running in the background after i log out from the shell.

**Comment by mrbrdo** [comment]
I have this too, when can we get a new version out?

**Comment by Mic92** [comment]
released

**Comment by npearson72** [comment]
@Mic92 Can you tag the release?

**Comment by Mic92** [comment]
I actually did, but forgot git push --tags

**Comment by npearson72** [comment]
Cool, thank you

**Comment by sandelius** [comment]
I still have the exact same problem with v0.3.1

**Comment by snitko** [comment]
This solution ended up helping me: http://www.codedisqus.com/CSVkXVUqVU/sidekiq-daemon-crashes-when-starting-with-mina.html

Basically, mina exits before a daemon is spawned. So it doesn't start. Thus it needs this sleep 1.

**Comment by Mic92** [comment]
@snitko this will still fails, if your system is under load and 1 sec is not enough. There might be a better alternative to nohup needed.

This is library is not longer maintained by me. If somebody wants to further develop it, please contact me:

[https://github.com/Mic92/mina-sidekiq#currently-unmaintained](https://github.com/Mic92/mina-sidekiq#currently-unmaintained)

Otherwise i would recommend the use of [capistrano3](http://capistranorb.com/) over mina, where the sidekiq module extension is maintained by the author of sidekiq itself.

**Comment by npearson72** [comment]
Here's how I do it.

Add this config file:

````
# /etc/init/sidekiq.conf - Sidekiq config

# This example config should work with Ubuntu 12.04+.  It
# allows you to manage multiple Sidekiq instances with
# Upstart, Ubuntu's native service management tool.
#
# See workers.conf for how to manage all Sidekiq instances at once.
#
# Save this config as /etc/init/sidekiq.conf then mange sidekiq with:
#   sudo start sidekiq index=0
#   sudo stop sidekiq index=0
#   sudo status sidekiq index=0
#
# or use the service command:
#   sudo service sidekiq {start,stop,restart,status}
#

description "Sidekiq Background Worker"

stop on (stopping workers or runlevel [06])

# change to match your deployment user
setuid {{server_user}}
setgid {{server_user}}
env HOME=/home/{{server_user}}

respawn
respawn limit 3 30

# TERM is sent by sidekiqctl when stopping sidekiq. Without declaring these as
# normal exit codes, it just respawns.
normal exit 0 TERM

instance $index
instance $environment

script
# this script runs in /bin/sh by default
# respawn as bash so we can source in rbenv
exec /bin/bash <<'EOT'
  source /home/{{server_user}}/.profile

  cd {{app_path}}
  bundle exec sidekiq -i ${index} -e ${environment} -C config/sidekiq.yml -L log/sidekiq.log
EOT
end script
````

Then in your mina deploy.rb

````

namespace :sidekiq do
  task start: :environment do
    queue %[echo "-----> Starting Sidekiq"]
    queue "sudo initctl start sidekiq index=0 environment=#{rails_env}"
  end

  task stop: :environment do
    queue %[echo "-----> Stopping Sidekiq"]
    queue "sudo initctl stop sidekiq environment=#{rails_env}"
  end

  task restart: :environment do
    invoke :"sidekiq:stop"
    invoke :"sidekiq:start"
  end
end

````

**Comment by Mic92** [comment]
@npearson72 much better, maybe I should just replace this gem by a description on how to use a supervisor (like upstart, systemd, supervisord). The only downside I see, is that your deploy user now needs root access to the server in question (or sudo). A wrapper around initctl just for sidekiq, with setuid bit set, might resolve this problem. If somebody of you uses systemd, the service file for gitlab's sidekiq might be worth checking out: https://github.com/gitlabhq/gitlab-recipes/blob/master/init/systemd/gitlab-sidekiq.service

**Comment by snitko** [comment]
Tha's exactly what I'm trying to avoid: not giving deploy user sudo privileges.

**Comment by Mic92** [comment]
@snitko you can restrict the user with sudo to just allow certain commands to be run as root:

Lets stay with the upstart example:

```bash
#!/bin/bash
#/usr/local/bin/sidekiq-service

case "$1" in
start)
  sudo initctl start sidekiq;;
stop)
  sudo initctl stop sidekiq;;
*)
  echo "USAGE: $0 start|stop";;
esac
```

Assuming that `deploy` is the deploy user put in `/etc/sudoers`:

```
deploy ALL = NOPASSWD: /usr/local/bin/sidekiq-service
```

```ruby
namespace :sidekiq do
  task start: :environment do
    queue %[echo "-----> Starting Sidekiq"]
    queue "sudo /usr/local/bin/sidekiq-service start"
  end

  task stop: :environment do
    queue %[echo "-----> Stopping Sidekiq"]
    queue "sudo /usr/local/bin/sidekiq-service stop"
  end

  task restart: :environment do
    invoke :"sidekiq:stop"
    invoke :"sidekiq:start"
  end
end
```
