### ISSUE TITLE
How to enable sidekiq.yml

### ISSUE THREAD

**Issue by jasper-fu** [Mic92/mina-sidekiq#7]
Hi, guys,

I don't know how to ask mina-sidekiq to use -c config/sidekiq.yml, is there any clue for this? thanks a lot

**Comment by jasper-fu** [comment]
Actually, I just need sidekiq to start like "sidekiq -q default -q mailer", and I don't know how can I do it with mina-sidekiq?

**Comment by Mic92** [comment]
Here is a example rails project: https://github.com/Mic92/mina-sidekiq-test-rails

**Comment by Mic92** [comment]
Either include in your `config/deploy.rb` or use `mina sidekiq:start`

**Comment by mperham** [comment]
Sidekiq explicitly looks for `config/sidekiq.yml` and uses it if found.  You don't need to explicitly list it on the command line.
